[build]
  # The example app lives in the "example" sub-directory.
  base = "example"

  # Standard build command defined in example/package.json
  command = "npm run build"

  # Vite outputs the static site to "dist" (relative to the base folder)
  publish = "dist"

  # Optional: pin the Node version used by Netlify’s build image
  [build.environment]
    NODE_VERSION = "22"

# Support client-side routing so refreshes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
